
title: CSS Grid in Production
email: me@rachelandrew.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This site is a list of websites that are using CSS Grid Layout in production. From a small component to the full layout. Add yours by submitting a pull request.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cssgrid.design" 
twitter_username: rachelandrew
github_username:  rachelandrew

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  gridsites:
    output: false
